apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/enigodupont/eniworks-kubernetes.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/calico
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
     - group: apiextensions.k8s.io
       kind: CustomResourceDefinition
       jsonPointers:
         - /spec/preserveUnknownFields
