apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  destination:
    namespace: operations
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://charts.jenkins.io"
    targetRevision: "4.3.22"
    chart: jenkins
    helm:
      values: |
        controller:
          ingress:
            enabled: true
            apiVersion: networking.k8s.io/v1
            hostName: jenkins.eniworks.net
            annotations:
              traefik.ingress.kubernetes.io/preserve-host: 'true'
          prometheus:
            enabled: true
          admin:
            existingSecret: jenkins
          installPlugins:
            - kubernetes:3883.v4d70a_a_a_df034
            - workflow-aggregator:581.v0c46fa_697ffd
            - git:5.0.0
            - configuration-as-code:1569.vb_72405b_80249
            - sonar:2.15
            - github:1.36.1
          resources:
            requests:
              cpu: "2"
              memory: "6Gi"
            limits:
              cpu: "2"
              memory: "6Gi"
          probes:
            livenessProbe:
              periodSeconds: 300

            
