apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  destination:
    namespace: operations
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://charts.jenkins.io"
    targetRevision: "4.1.4"
    chart: jenkins
    helm:
      values: |
        controller:
          ingress:
            enabled: true
            apiVersion: networking.k8s.io/v1
            hostName: jenkins.eniworks.net
            annotations:
              traefik.ingress.kubernetes.io/preserve-host: 'true'
          prometheus:
            enabled: true
          admin:
            existingSecret: jenkins
          installPlugins:
            - kubernetes:3600.v144b_cd192ca_a_
            - workflow-aggregator:581.v0c46fa_697ffd
            - git:4.11.3
            - configuration-as-code:1429.v09b_044a_c93de
            - sonar:2.14
            