apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  destination:
    namespace: operations
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://charts.jenkins.io"
    targetRevision: 5.8.116
    chart: jenkins
    helm:
      values: |
        controller:
          ingress:
            enabled: true
            apiVersion: networking.k8s.io/v1
            hostName: jenkins.eniworks.net
            annotations:
              traefik.ingress.kubernetes.io/preserve-host: 'true'
          prometheus:
            enabled: true
          admin:
            existingSecret: jenkins
          installPlugins:
            # Jenkins complains about the following after 2025
            - commons-text-api:1.15.0-210.v7480a_da_70b_9e
            - plugin-util-api:6.1167.v022176c7e0ca_
            - bootstrap5-api:5.3.8-876.vb_c62a_27d9a_77
            - font-awesome-api:7.0.1-859.v128d3a_efb_6e5
            - eddsa-api:0.3.0.1-19.vc432d923e5ee
            - git-client:6.3.3
            # These were here before
            - kubernetes:4371.vb_33b_086d54a_1
            - workflow-aggregator:608.v67378e9d3db_1
            - git:5.7.0
            - configuration-as-code:2006.v001a_2ca_6b_574
            - sonar:2.18
            - github:1.45.0
            - simple-theme-plugin:211.v5424a_5510e47
            - cloudbees-disk-usage-simple:256.v20ec4eb_884f1
          resources:
            requests:
              cpu: "2"
              memory: "6Gi"
            limits:
              cpu: "2"
              memory: "6Gi"
          probes:
            livenessProbe:
              periodSeconds: 60
            startupProbe:
              periodSeconds: 60

            
