apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  destination:
    namespace: operations
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://charts.jenkins.io"
    targetRevision: 5.9.12
    chart: jenkins
    helm:
      values: |
        controller:
          ingress:
            enabled: true
            apiVersion: networking.k8s.io/v1
            hostName: jenkins.eniworks.net
            annotations:
              traefik.ingress.kubernetes.io/preserve-host: 'true'
          prometheus:
            enabled: true
          admin:
            existingSecret: jenkins
          installPlugins:
            # Jenkins complains about the following after 2025
            - commons-text-api:1.15.0-218.va_61573470393
            - plugin-util-api:6.1192.v30fe6e2837ff
            - bootstrap5-api:5.3.8-895.v4d0d8e47fea_d
            - font-awesome-api:7.1.0-882.v1dfb_771e3278
            - eddsa-api:0.3.0.1-19.vc432d923e5ee
            - git-client:6.3.3
            # These were here before
            - kubernetes:4371.vb_33b_086d54a_1
            - workflow-aggregator:608.v67378e9d3db_1
            - git:5.7.0
            - configuration-as-code:2053.vb_0da_47381a_25
            - sonar:2.18
            - github:1.45.0
            - simple-theme-plugin:211.v5424a_5510e47
            - cloudbees-disk-usage-simple:256.v20ec4eb_884f1
            # Added to prevent drifting upgrades
            - credentials:1502.v5c95e620ddfe
          resources:
            requests:
              cpu: "2"
              memory: "6Gi"
            limits:
              cpu: "2"
              memory: "6Gi"
          probes:
            livenessProbe:
              periodSeconds: 60
            startupProbe:
              periodSeconds: 60

            
