apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix
  namespace: argocd
spec:
  project: default
  destination:
    namespace: operations
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/startupProbe
  source:
    repoURL: "registry-1.docker.io"
    targetRevision: "2.8.0"
    chart: enigodupont/matrix
    helm:
      values: |
        postgresql:
          enabled: false
          hostname: 10.64.0.6
          auth:
            username: matrix
            password: not_real_value_wont_work_override
        coturn:
          enabled: false
          service:
            type: ClusterIP
        networkPolicies:
          enabled: false
        ingress:
          enabled: false
          hosts:
            federation: matrix-fed.eniworks.net
            riot: element.eniworks.net
            synapse: matrix.eniworks.net
        mail:
          external:
            host: '10.64.0.6'
            requireTransportSecurity: false
        matrix:
          serverName: eniworks.net
          registration:
            enabled: false
            allowGuests: false
            sharedSecret: ''
          adminEmail: juramir@protonmail.com
          security:
            trustedKeyServers:
              - serverName: matrix.org
        riot:
          enabled: false
        synapse:
          image:
            tag: v1.129.0 # Latest is 1.140.0
          resources:
            requests:
              cpu: 250m
              memory: 2Gi
            limits: 
              cpu: 250m
              memory: 2Gi   
          probes:
            readiness:
              timeoutSeconds: 30
              periodSeconds: 30
            startup:
              timeoutSeconds: 30
              periodSeconds: 30
              failureThreshold: 6
            liveness:
              timeoutSeconds: 30
              periodSeconds: 30
