apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-addons
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/enigodupont/eniworks-kubernetes.git
    targetRevision: HEAD
    path: kubernetes/matrix-addons