apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 3.2.2
    chart: prometheus-adapter
    helm:
      parameters:
        - name: prometheus.url
          value: 'http://prometheus-operated.monitoring.svc.cluster.local'
