apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: version-checker
  namespace: argocd
spec:
  project: default
  destination:
    namespace: operations
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://charts.jetstack.io"
    targetRevision: v0.10.0
    chart: version-checker
    helm:
      values: |
        dashboards:
          enabled: true      
          labels:
            grafana_dashboard: '1'   
