apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`jenkins.eniworks.net`)
    kind: Rule
    services:
    - name: jenkins-operator-http-jenkins
      port: 8080
      passHostHeader: true