apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: operations
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.319.1-lts-alpine
        imagePullPolicy: Always
        # livenessProbe:
        #   failureThreshold: 10
        #   httpGet:
        #     path: /login
        #     port: http
        #     scheme: HTTP
        #   initialDelaySeconds: 300
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 15
        # readinessProbe:
        #   failureThreshold: 10
        #   httpGet:
        #     path: /login
        #     port: http
        #     scheme: HTTP
        #   initialDelaySeconds: 300
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 15
        resources:
          limits:
            cpu: '4'
            memory: 12Gi
          requests:
            cpu: '4'
            memory: 12Gi