kind: Ingress
apiVersion: networking.k8s.io/v1 
metadata:
  name: argo
  namespace: argocd
spec:
  rules:
    - host: argo.eniworks.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port: 
                number: 443
