---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicbot
  labels:
    run: musicbot
spec:
  replicas: 1
  selector:
    matchLabels:
      run: musicbot
  template:
    metadata:
      labels:
        run: musicbot
    spec:
      containers:
      - name: musicbot
        #image: enigodupont/musicbot:latest
        image: ghcr.io/museofficial/muse:pr-1197
        imagePullPolicy: Always
        env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: muse-config
                key: DISCORD_TOKEN
          - name: YOUTUBE_API_KEY
            valueFrom:
              secretKeyRef:
                name: muse-config
                key: YOUTUBE_API_KEY
        resources:
          requests:
            memory: "400Mi"
            cpu: 500m
          limits:
            memory: "400Mi"
            cpu: 500m
        #volumeMounts:
        #- mountPath: "/app/config.txt"
        #  subPath: "config.txt"
        #  readOnly: true
        #  name: musicbot-config
      #volumes:
      #- name: musicbot-config
      #  secret:
      #    secretName: musicbot-config
