apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`argo.eniworks.net`)
      services:
        - kind: Service
          name: argocd-server
          passHostHeader: true
          port: 443
