apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`argo.eniworks.net`)
    kind: Rule
    services:
    - name: argocd-server
      port: 443
      passHostHeader: true