apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  serviceName: "minecraft"
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: enigodupont/papermc:latest
          env:
            - name: "MC_VERSION"
              value: "1.19.2"
            - name: "MC_RAM"
              value: "6G"
            - name: "JAVA_OPTS"
              value: >-
                -XX:+UseG1GC -Dlog4j2.formatMsgNoLookups=true
                -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200
                -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC
                -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30
                -XX:G1MaxNewSizePercent=40  -XX:G1HeapRegionSize=8M
                -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5
                -XX:G1MixedGCCountTarget=4 
                -XX:InitiatingHeapOccupancyPercent=15
                -XX:G1MixedGCLiveThresholdPercent=90
                -XX:G1RSetUpdatingPauseTimePercent=5  -XX:SurvivorRatio=32
                -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
                -Dusing.aikars.flags=https://mcflags.emc.gs
                -Daikars.new.flags=true
          imagePullPolicy: Always 
          ports:
            - containerPort: 25565
            - containerPort: 8123
            - containerPort: 19132
          volumeMounts:
            - mountPath: "/papermc"
              name: minecraft-data
          resources:
            limits:
              cpu: '2'
              memory: 8Gi
            requests:
              cpu: '2'
              memory: 8Gi
  volumeClaimTemplates:
  - metadata:
      name: minecraft-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - name: mc-port
      protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 32556
    - name: mc-geyser-port
      protocol: UDP
      port: 19132
      targetPort: 19132 
      nodePort: 31329 
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-ui
spec:
  selector:
    app: minecraft
  ports:
    - name: ui-port
      protocol: TCP
      port: 8123
      targetPort: 8123
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minecraft-ui
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`minecraft.eniworks.net`)
    kind: Rule
    services:
    - name: minecraft-ui
      port: 8123
      passHostHeader: true
