apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  serviceName: "minecraft"
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: phyremaster/papermc
          env:
            - name: "MC_VERSION"
              value: "1.17.1"
            - name: "MC_RAM"
              value: "4G"
            - name: "JAVA_OPTS"
              value: "-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dlog4j2.formatMsgNoLookups=true"
          imagePullPolicy: Always 
          ports:
            - containerPort: 25565
            - containerPort: 8123
            - containerPort: 19132
          volumeMounts:
            - mountPath: "/papermc"
              name: minecraft-data
          resources:
            requests:
              memory: "4Gi"
              cpu: 2 
            limits:
              memory: "5Gi"
              cpu: 2
  volumeClaimTemplates:
  - metadata:
      name: minecraft-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - name: mc-port
      protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 32556
    - name: mc-geyser-port
      protocol: UDP
      port: 19132
      targetPort: 19132 
      nodePort: 31329 
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-ui
spec:
  selector:
    app: minecraft
  ports:
    - name: ui-port
      protocol: TCP
      port: 8123
      targetPort: 8123
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1 
metadata:
  name: minecraft-ui
spec:
  rules:
    - host: minecraft.eniworks.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: minecraft-ui
              port: 
                number: 8123
