apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  serviceName: "minecraft"
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: hchasens/papermc@sha256:ec0518710efe27fb8cde3149e31cb2d1a334f628b335797896e2978b7ab34ca6
          env:
            - name: "MC_VERSION"
              value: "1.18.2"
            - name: "MC_RAM"
              value: "4G"
            - name: "JAVA_OPTS"
              value: "-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dlog4j2.formatMsgNoLookups=true"
          imagePullPolicy: Always 
          ports:
            - containerPort: 25565
            - containerPort: 8123
            - containerPort: 19132
          volumeMounts:
            - mountPath: "/papermc"
              name: minecraft-data
          resources:
            requests:
              memory: "4Gi"
              cpu: 2 
            limits:
              memory: "5Gi"
              cpu: 2
  volumeClaimTemplates:
  - metadata:
      name: minecraft-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - name: mc-port
      protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 32556
    - name: mc-geyser-port
      protocol: UDP
      port: 19132
      targetPort: 19132 
      nodePort: 31329 
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-ui
spec:
  selector:
    app: minecraft
  ports:
    - name: ui-port
      protocol: TCP
      port: 8123
      targetPort: 8123
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minecraft-ui
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`minecraft.eniworks.net`)
    kind: Rule
    services:
    - name: minecraft-ui
      port: 8123
      passHostHeader: true
