apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/eniworks.yaml
  - infra/nfs-client-provisioner.yaml
  - infra/kube-prometheus-stack.yaml
  - infra/prometheus-adapter.yaml
  - infra/traefik.yaml
  - infra/traefik-monitoring.yaml
  - infra/elastic-operator.yaml
  - infra/elastic-logs.yaml
  - infra/argo-addons.yaml
  - infra/docker-registry.yaml
  - infra/matrix.yaml
  - infra/matrix-addons.yaml
  - infra/jenkins-operator.yaml
  # Holding on jenkins install as it currently needs 10+Gi Ram
  #- infra/jenkins.yaml
  - apps/media.yaml
  - apps/games.yaml
  - apps/dndashboard.yaml