apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/argo.yaml
  - infra/calico.yaml
  - infra/democratic-csi.yaml
  - infra/eniworks.yaml
  - infra/nfs-client-provisioner.yaml
  - infra/kube-prometheus-stack.yaml
  - infra/prometheus-adapter.yaml
  - infra/traefik.yaml
  - infra/traefik-monitoring.yaml
  - infra/elastic-operator.yaml
  - infra/elastic-logs.yaml
  # This registry didn't fit my needs, not deploying for now.
  #- infra/docker-registry.yaml
  - infra/matrix.yaml
  - infra/matrix-addons.yaml
  - infra/jenkins.yaml
  - infra/sonarqube.yaml
  - infra/umami.yaml
  - infra/ghost.yaml
  - infra/filestash.yaml
  - infra/DirectoryLister.yaml
  - infra/bluesky-pds.yaml
  - infra/vert.yaml
  - apps/media.yaml
  - apps/games.yaml
  - apps/dndashboard.yaml
  - apps/roadtripfinder.yaml
  - apps/smt.yaml
  - apps/logintracker.yaml
  - distributed-llama/distributed-llama.yaml
