apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/eniworks.yaml
  - infra/nfs-client-provisioner.yaml
  - infra/kube-prometheus-stack.yaml
  - infra/traefik.yaml
  - infra/elastic-operator.yaml
  - infra/elastic-logs.yaml
  - infra/argo-addons.yaml
  - apps/media.yaml
  - apps/games.yaml
  - apps/dndashboard.yaml