apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - eniworks.yaml
  - nfs-client-provisioner.yaml
  - kube-prometheus-stack.yaml
  - traefik.yaml
  - elastic-operator.yaml
  - elastic-logs.yaml
  - media.yaml
  - argo-addons.yaml