kind: Ingress
apiVersion: networking.k8s.io/v1 
metadata:
  name: kibana
spec:
  rules:
    - host: kibana.eniworks.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: logs-kb-http
              port: 
                number: 5601
