apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kibana
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`kibana.eniworks.net`)
    kind: Rule
    services:
    - name: logs-kb-http
      port: 5601
      passHostHeader: true