apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logs
spec:
  version: 8.17.4
  count: 1
  elasticsearchRef:
    name: logs
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 1Gi