apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matrix
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`matrix.eniworks.net`)
    kind: Rule
    services:
    - name: matrix-synapse
      port: 80
      passHostHeader: true
  - match: Host(`matrix-fed.eniworks.net`)
    kind: Rule
    services:
    - name: matrix-synapse-federation
      port: 80
      passHostHeader: true
    # Riot rule
    #- match: Host(`element.eniworks.net`)
    #  kind: Rule
    #  services:
    #   - name: matrix-riot
    #     port: 80
    #     passHostHeader: true