apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: umami
  labels:
    app: umami
spec:
  replicas: 1
  serviceName: "umami"
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - name: umami
          image: ghcr.io/mikecao/umami:postgresql-v1.31.0
          env:
            - name: DATABASE_TYPE
              value: postgresql
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: umami-config
                  key: DATABASE_URL
            - name: HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: umami-config
                  key: HASH_SALT
          imagePullPolicy: Always 
          ports:
            - containerPort: 3000
              name: ui
---
apiVersion: v1
kind: Service
metadata:
  name: umami
spec:
  selector:
    app: umami
  ports:
    - name: ui
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: umami
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`umami.eniworks.net`)
    kind: Rule
    services:
    - name: umami
      port: 3000
      passHostHeader: true